CHANGELOG.md
dockerImages.yml

Update cutadapt to 2.4

---

dockerImages.yml

Remove unused fastqsplitter image

---

.github/PULL_REQUEST_TEMPLATE.md
.gitmodules
CHANGELOG.md
docs/index.md
pipeline.wdl

Documentation up to date.

---

CHANGELOG.md
dockerImages.yml
docs/index.md
pipeline.wdl
readgroup.wdl
tests/integration/SingleEndHisat2.json
tests/integration/SingleEndLncRna.json
tests/integration/SingleEndVariantCalling.json
tests/samplesheets/Rna3SingleEnd.csv
tests/samplesheets/Rna3SingleEnd.yml

Allow CSV inputs

---

.gitmodules
CHANGELOG.md
dockerImages.yml
pipeline.wdl
sample.wdl

Remove gatk-preprocess and bam-to-gvcf in favour of gatk-variantcalling.

---

.travis.yml
pipeline.wdl
requirements-test.txt

add miniwdl check to testing

---

CHANGELOG.md
dockerImages.yml

Update default htseq image version to 0.11.2

---

.travis.yml
CHANGELOG.md
docs/index.md
docs/inputs.md
pipeline.wdl
requirements-test.txt
sample.wdl

add input overview to docs

---

CHANGELOG.md
dockerImages.yml
docs/index.md
docs/inputs.md
pipeline.wdl
sample.wdl
tests/integration/PairedEndHisat2.json
tests/integration/PairedEndHisat2AndStar.json
tests/integration/PairedEndLncRna.json
tests/integration/PairedEndVariantCalling.json
tests/integration/SingleEndHisat2.json
tests/integration/SingleEndLncRna.json
tests/integration/SingleEndVariantCalling.json

Fix the errors in RNA variantcalling. Remove structs.

---

docs/inputs.md
pipeline.wdl
structs.wdl

This consolidates the scatterregions tasks. It also enables gender-aware variantcalling (as a subworkflow option).

Update submodules and inputs

---

CHANGELOG.md
pipeline.wdl
sample.wdl
structs.wdl

Make sure every file has license headers.

---

CHANGELOG.md
pipeline.wdl
requirements-test.txt
tests/integration/SingleEndVariantCalling.json
tests/test_pipelines.yml

I need this for an analysis where the GVCFs are important to get the correct results.

allow jointgenotyping

---

CHANGELOG.md
docs/index.md
pipeline.wdl

Add global scattersize option.

---

CHANGELOG.md
sample.wdl

make UMI deduplication stat collection optional

---

docs/index.md
docs/inputs.md

prepare for release 3.0.0

---

.gitignore
CHANGELOG.md
docs/index.md
pipeline.wdl
tests/integration/SingleEndVariantCalling.json
tests/test_pipelines.yml

Implement best practices for single sample RNA calling.

---

CHANGELOG.md
RNA-seq.wdl
docs/index.md
tests/functional/PairedEndLncRna.json
tests/functional/PairedEndVariantCalling.json
tests/integration/PairedEndHisat2.json
tests/integration/PairedEndHisat2AndStar.json
tests/integration/PairedEndLncRna.json
tests/integration/PairedEndUmi.json
tests/integration/PairedEndVariantCalling.json
tests/integration/SingleEndHisat2.json
tests/integration/SingleEndLncRna.json
tests/integration/SingleEndUmi.json
tests/integration/SingleEndVariantCalling.json
tests/test_pipelines.yml

rename pipeline to RNAseq

---

.travis.yml
CHANGELOG.md
RNA-seq.wdl
dockerImages.yml
tests/test_pipelines.yml

Problems with resource requirements have been largely addressed in the submodules.

Address resource requirements in RNA-seq

---

CHANGELOG.md
RNA-seq.wdl
docs/index.md
sample.wdl
tests/test_pipelines.yml

Simplify output directory.

---

CHANGELOG.md
docs/index.md

Add instructions on how to run with imports zip

---

CHANGELOG.md
RNA-seq.wdl
dockerImages.yml

Downgrade stringtie to version 1.3.6.

---

CHANGELOG.md
dockerImages.yml
tests/cromwell_options.json

Update docker image with umi samtools

---

CHANGELOG.md
dockerImages.yml

update dockerimages: umitools

---

CHANGELOG.md
RNA-seq.wdl
dockerImages.yml

Add new optional calls for dge files
